### ISSUE TITLE
v3 Configuration Engine

### ISSUE THREAD

**Issue by akurilov** [emc-mongoose/mongoose#14]
Implement the configuration engine for the following modules:
1. Common
2. Driver
3. Generator
4. Monitor
3. StorageMock

See the module-specific configuration in the <MODULE_NAME>/src/main/resources/defaults.json.
The module-specific configuration should be loaded into the corresponding <MODULE_NAME>Config class, for example:
1. CommonConfig
2. DriverConfig
3. GeneratorConfig
4. MonitorConfig
5. StorageMockConfig

**Comment by kisliakovsky** [comment]
Done!
