### ISSUE TITLE
no way to stop wsmock which was started with nohup

### ISSUE THREAD

**Issue by azhagarasu** [emc-mongoose/mongoose#35]
There is no way to stop wsmock test started as a background process. There is no kill switch.

`nohup java -jar mongoose.jar wsmock > test.out &`

It is continuously running. Killing JAVA process didn't help.

**Comment by azhagarasu** [comment]
Each nohup commands assigns a PID. Killing the PID will terminate the job. To get a list of PID.

`ps -ef`

**Comment by akurilov** [comment]
Pressing Ctrl+C will interrupt the web storage mock

**Comment by azhagarasu** [comment]
@akurilov there is no way to press ctrl+C when the command is ran using `nohup`

**Comment by akurilov** [comment]
try "kill -9 <PID>" where PID is a corresponding java process id
