### ISSUE TITLE
WebUI - Reload page clears custom settings to default values

### ISSUE THREAD

**Issue by kevkha** [emc-mongoose/mongoose#51]
I'm running Mongoose webui 2.5.5 in docker container and observe that when reloading the page, custom values under `Scenarios` and `Defaults` tabs are reverted back to default values. Is this expected behavior or I need to map a docker volume to make the data persistent?

**Comment by akurilov** [comment]
Hi. I was able to reproduce the issue. I think that this data should be persisted in the session cookies so this is a bug. As a workaround you can save the modified scenario or the modified "defaults" configuration (see "Save" button left of the "Start" one).

**Comment by akurilov** [comment]
Mongoose 2.x is not supported anymore. The 3.x GUI is upcoming. Could this issue be closed?

**Comment by kevkha** [comment]
Make sense. Closing it. Thanks.
