### ISSUE TITLE
Item output path for bucket

### ISSUE THREAD

**Issue by kevkha** [emc-mongoose/mongoose#54]
In release 3.x we notice that it accepts a bucket name for `---item-output-path` but must use with a `/`

Example: `--item-output-path=/test_bucket`

Not too user friendly to some users. Is it possible to hard code the `/` so that users simply just specify the bucket name without the `/`?

**Comment by akurilov** [comment]
Hi. This was fixed in the version 3.1.0. Please use it.

**Comment by kevkha** [comment]
Thanks @akurilov. Confirmed that fixed in 3.1.0 and latest. Closing.
