### ISSUE TITLE
Random log folder is created even though option load-job-name is used

### ISSUE THREAD

**Issue by kevkha** [emc-mongoose/mongoose#56]
Random log folder is created even though option `--load-job-name` is used. Observed that the `messages.log` is found in both folders with different contents and sizes. This might lead to confusion when reviewing the logs.
```
/opt/mongoose/log # ls -l
total 8
drwxr-xr-x 2 root root 4096 Feb 22 03:00 2017.02.22.08.00.48.972
drwxr-xr-x 2 root root 4096 Feb 22 03:00 demo-create

/opt/mongoose/log # ls -l 2017.02.22.08.00.48.972
total 4
-rw-r--r-- 1 root root 298 Feb 22 03:00 messages.log

/opt/mongoose/log # ls -l demo-create
total 16
-rw-r--r-- 1 root root 6021 Feb 22 03:00 3rdparty.log
-rw-r--r-- 1 root root 3443 Feb 22 03:00 messages.log
-rw-r--r-- 1 root root  437 Feb 22 03:00 metrics.csv
-rw-r--r-- 1 root root    0 Feb 22 03:00 metrics.total.csv
```

**Comment by akurilov** [comment]
Confirming this behavior. Some log statements are executed before the load job name is set. These log messages are treated as out of context of the configured load job.

**Comment by akurilov** [comment]
Current approach is a bit legacy. Initially mongoose was not designed to run more than one job/step per run. But later the scenario engine was introduced and the property named "run-id" became a "load-job-name". Currently it is named "test-step-name". I think that it's most convenient to use both run id (to differentiate the launches) and [scenario] step id. This will allow to make the run id initialized with a timestamp (always, unconfigurable). The step id may be initialized by user via configuration either automatically using ordinal step number.

**Comment by akurilov** [comment]
@kevkha 
Hi, could you please clarify if it's reproducible using v3.4.1?
Thanks

**Comment by kevkha** [comment]
No longer an issue with 3.5.0. Closing issue. Thanks.
